# Example ExternalSecret that syncs secrets from Vault to Kubernetes

# Create a secret in Vault first:
# vault kv put secret/myapp/database username=admin password=secret123 host=db.example.com

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: production
spec:
  # Refresh interval
  refreshInterval: 1h

  # Secret store reference
  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  # Target Kubernetes secret
  target:
    name: database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: myapp
        annotations:
          reloader.stakater.com/match: "true"
      data:
        # Simple key mapping
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
        DB_HOST: "{{ .host }}"

        # Templated connection string
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@{{ .host }}:5432/myapp"

  # Data to fetch from Vault
  data:
    - secretKey: username
      remoteRef:
        key: secret/myapp/database
        property: username

    - secretKey: password
      remoteRef:
        key: secret/myapp/database
        property: password

    - secretKey: host
      remoteRef:
        key: secret/myapp/database
        property: host
---
# Example: Syncing entire secret (all key-value pairs)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-credentials
  namespace: production
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: api-credentials
    creationPolicy: Owner
  # Sync all keys from the Vault secret
  dataFrom:
    - extract:
        key: secret/myapp/api
---
# Example: Using ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-config
  namespace: production
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: shared-config
    creationPolicy: Owner
  data:
    - secretKey: jwt-secret
      remoteRef:
        key: secret/shared/config
        property: jwt_secret
---
# ConfigMap to document Vault setup
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-eso-setup
  namespace: external-secrets-system
data:
  setup-vault.sh: |
    #!/bin/bash
    set -e

    echo "Setting up Vault for External Secrets Operator..."

    # Wait for Vault
    until vault status; do
      echo "Waiting for Vault..."
      sleep 5
    done

    # Enable Kubernetes auth if not already enabled
    vault auth enable kubernetes 2>/dev/null || true

    # Configure Kubernetes auth
    vault write auth/kubernetes/config \
      kubernetes_host="https://kubernetes.default.svc:443"

    # Create policy for External Secrets Operator
    vault policy write external-secrets-policy - <<EOF
    path "secret/data/*" {
      capabilities = ["read", "list"]
    }
    path "secret/metadata/*" {
      capabilities = ["read", "list"]
    }
    EOF

    # Create role for external-secrets service account
    vault write auth/kubernetes/role/external-secrets \
      bound_service_account_names=external-secrets \
      bound_service_account_namespaces=external-secrets-system \
      policies=external-secrets-policy \
      ttl=24h

    # Create policies for application namespaces
    for env in production staging development; do
      vault policy write ${env}-apps-policy - <<EOF
    path "secret/data/${env}/*" {
      capabilities = ["read", "list"]
    }
    path "secret/data/shared/*" {
      capabilities = ["read", "list"]
    }
    EOF

      vault write auth/kubernetes/role/${env}-apps \
        bound_service_account_names=default \
        bound_service_account_namespaces=${env} \
        policies=${env}-apps-policy \
        ttl=24h
    done

    # Create example secrets
    vault kv put secret/production/myapp/database \
      username=admin \
      password=production-secret-123 \
      host=prod-db.example.com

    vault kv put secret/staging/myapp/database \
      username=admin \
      password=staging-secret-123 \
      host=staging-db.example.com

    vault kv put secret/development/myapp/database \
      username=admin \
      password=dev-secret-123 \
      host=dev-db.example.com

    vault kv put secret/shared/config \
      jwt_secret=shared-jwt-secret-key

    echo "Vault setup for External Secrets Operator completed!"
    echo ""
    echo "Example secrets created:"
    echo "  - secret/production/myapp/database"
    echo "  - secret/staging/myapp/database"
    echo "  - secret/development/myapp/database"
    echo "  - secret/shared/config"
