apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-microservice-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    environment: production
    app: my-microservice
spec:
  project: default

  source:
    # Reference to the Helm chart in the Git repository
    repoURL: https://github.com/YOUR_ORG/gitops-platform.git  # UPDATE THIS
    targetRevision: HEAD
    path: charts/my-microservice
    helm:
      # Use production-specific values
      valueFiles:
        - ci/production-values.yaml

      # Override specific values if needed
      values: |
        replicaCount: 5

        image:
          repository: YOUR_ECR_REGISTRY/my-microservice  # UPDATE THIS
          tag: "1.0.0"  # Updated by CI/CD

        ingress:
          enabled: true
          hosts:
            - host: myapp.example.com  # UPDATE THIS
              paths:
                - path: /
                  pathType: Prefix

        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 256Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: production

  syncPolicy:
    automated:
      prune: true      # Remove resources that are no longer defined in Git
      selfHeal: true   # Revert manual changes back to Git state
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Health assessment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Ignore replicas if using HPA

  # Notification annotations
  info:
    - name: 'Environment'
      value: 'Production'
    - name: 'Owner'
      value: 'Platform Team'
    - name: 'Slack Channel'
      value: '#production-alerts'
