apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  annotations:
    cert-manager.io/inject-ca-from: linkerd/linkerd-trust-anchor
data:
  ca-bundle.crt: ""
