apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    # Source 1: Helm Chart
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-control-plane
      targetRevision: 1.16.11
      helm:
        releaseName: linkerd-control-plane
        valuesObject:
          identity:
            issuer:
              scheme: kubernetes.io/tls
          controllerReplicas: 1  # Single node K3s
          controllerResources:
            cpu:
              request: 100m
            memory:
              request: 128Mi
            limit:
              cpu: 1000m
              memory: 1Gi
          destinationResources:
            cpu:
              request: 100m
            memory:
              request: 128Mi
            limit:
              cpu: 1000m
              memory: 512Mi
          proxy:
            enableExternalProfiles: true
            resources:
              cpu:
                request: 100m
              memory:
                request: 128Mi
              limit:
                cpu: 500m
                memory: 256Mi
          proxyInjector:
            externalSecret: false
            resources:
              cpu:
                request: 100m
              memory:
                request: 128Mi
              limit:
                cpu: 500m
                memory: 256Mi
          profileValidator:
            externalSecret: false
            resources:
              cpu:
                request: 100m
              memory:
                request: 128Mi
              limit:
                cpu: 500m
                memory: 256Mi
          policyValidator:
            externalSecret: false
            resources:
              cpu:
                request: 100m
              memory:
                request: 128Mi
              limit:
                cpu: 500m
                memory: 256Mi
          disableHeartBeat: false
          enablePodAntiAffinity: false  # Disabled for single node

    # Source 2: Kustomize Overlay
    - repoURL: https://github.com/oNddleo/gitops.git
      targetRevision: HEAD
      path: infrastructure/linkerd/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
