apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    # Source 1: Helm Chart
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-viz
      targetRevision: 2025.11.3
      helm:
        releaseName: linkerd-viz
        valuesObject:
          dashboard:
            replicas: 1  # Single node K3s
            resources:
              cpu:
                request: 50m
              memory:
                request: 128Mi
              limit:
                cpu: 500m
                memory: 512Mi
          prometheus:
            enabled: true
            resources:
              cpu:
                request: 300m
              memory:
                request: 512Mi
              limit:
                cpu: 1000m
                memory: 2Gi
          grafana:
            enabled: true
            resources:
              cpu:
                request: 50m
              memory:
                request: 128Mi
              limit:
                cpu: 500m
                memory: 512Mi

    # Source 2: Kustomize Overlay
    - repoURL: https://github.com/oNddleo/gitops.git
      targetRevision: HEAD
      path: infrastructure/linkerd-viz/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd-viz
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
