apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reloader
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: reloader
    repoURL: https://stakater.github.io/stakater-charts
    targetRevision: 1.0.79
    helm:
      releaseName: reloader
      valuesObject:
        reloader:
          watchGlobally: true
          ignoreNamespaces: "kube-system,kube-public,kube-node-lease"
          syncAfterRestart: true
          deployment:
            replicas: 1  # Single node K3s
            resources:
              limits:
                cpu: 100m
                memory: 128Mi
              requests:
                cpu: 10m
                memory: 32Mi
            securityContext:
              runAsNonRoot: true
              runAsUser: 65534
            podSecurityContext:
              fsGroup: 65534
          enableMetrics: true
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus
          autoReloadAll: false
          logFormat: json
  destination:
    server: https://kubernetes.default.svc
    namespace: reloader
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
