apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    # Source 1: Helm Chart
    - repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      chart: secrets-store-csi-driver
      targetRevision: 1.5.4
      helm:
        releaseName: secrets-store-csi-driver
        valuesObject:
          syncSecret:
            enabled: true
          enableSecretRotation: true
          rotationPollInterval: "120s"
          serviceAccount:
            create: true
            name: secrets-store-csi-driver
            annotations:
              eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/gitops-eks-cluster-secrets-csi-driver"  # UPDATE THIS
          linux:
            resources:
              limits:
                cpu: 200m
                memory: 200Mi
              requests:
                cpu: 50m
                memory: 100Mi
          enableMetrics: true
          logVerbosity: 2

    # Source 2: Kustomize Overlay
    - repoURL: https://github.com/oNddleo/gitops.git
      targetRevision: HEAD
      path: infrastructure/secrets-store-csi/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
